export const INITIALIZE = "INITIALIZE";
export const INITIALIZE_SUCCESS = "INITIALIZE_SUCCESS";
export const INITIALIZE_ERROR = "INITIALIZE_ERROR";

export const REQUEST_FIREBASE = "REQUEST_FIREBASE";
export const RECIEVED_FIREBASE = "RECIEVED_FIREBASE";
export const RECIEVED_FIREBASE_ERROR = "RECIEVED_FIREBASE_ERROR";
export const CLEAR_FIREBASE = "CLEAR_FIREBASE";

export const REQUEST_CREATE_ACCOUNT = "REQUEST_CREATE_ACCOUNT";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAILURE = "CREATE_ACCOUNT_FAILURE";

export const REQUEST_SIGN_IN = "REQUEST_SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

export const REQUEST_SIGN_OUT = "REQUEST_SIGN_OUT";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";
